In [1]:
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()
y = digits.target == 9

In [3]:
y

array([False, False, False, ..., False,  True, False], dtype=bool)

In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(digits.data,y,random_state=0)

In [7]:
from sklearn.dummy import DummyClassifier

dummy_majority = DummyClassifier(strategy='most_frequent').fit(x_train,y_train)
pred_most_frequent = dummy_majority.predict(x_test)

In [10]:
import numpy as np

print(np.unique(pred_most_frequent))
print(dummy_majority.score(x_test,y_test))

[False]
0.895555555556


In [13]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=2).fit(x_train,y_train)
pred_tree = tree.predict(x_test)

print(tree.score(x_test,y_test))

0.917777777778


In [14]:
from sklearn.linear_model import LogisticRegression

dummy = DummyClassifier().fit(x_train,y_train)
pred_dummy = dummy.predict(x_test)

print(dummy.score(x_test,y_test))

logreg = LogisticRegression(C=0.1).fit(x_train,y_train)
pred_logreg = logreg.predict(x_test)
print(logreg.score(x_test,y_test))

0.813333333333
0.977777777778


# confusion matrix

In [15]:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test,pred_logreg)
print(confusion)

[[401   2]
 [  8  39]]


In [23]:
print('빈도 기반 더미')
print(confusion_matrix(y_test,pred_most_frequent))
print('\n무작위 더미')
print(confusion_matrix(y_test,pred_dummy))
print('\n결정 트리')
print(confusion_matrix(y_test,pred_tree))
print('\n로지스틱 회귀')
print(confusion_matrix(y_test,pred_logreg))

빈도 기반 더미
[[403   0]
 [ 47   0]]

무작위 더미
[[361  42]
 [ 44   3]]

결정 트리
[[390  13]
 [ 24  23]]

로지스틱 회귀
[[401   2]
 [  8  39]]


In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred_most_frequent,target_names=['9아님','9']))

             precision    recall  f1-score   support

        9아님       0.90      1.00      0.94       403
          9       0.00      0.00      0.00        47

avg / total       0.80      0.90      0.85       450



E:\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [26]:
print(classification_report(y_test,pred_logreg,target_names=['9아님','9']))

             precision    recall  f1-score   support

        9아님       0.98      1.00      0.99       403
          9       0.95      0.83      0.89        47

avg / total       0.98      0.98      0.98       450

