In [1]:
import numpy as np

In [2]:
data = np.loadtxt('movielens-1m/ratings.dat',delimiter='::',dtype=np.int64)

In [5]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [4]:
data.shape

(1000209, 4)

In [6]:
# 전체 평균 평점 계산

mean_rate = data[:,2].mean()
print(mean_rate)


3.58156445303


In [7]:
user_id = np.unique(data[:,0])

In [8]:
user_id[:5]

array([1, 2, 3, 4, 5], dtype=int64)

In [9]:
user_id.shape

(6040,)

In [14]:
mean_rate_user = []

for user in user_id:
    data_for_user = data[data[:,0] == user,:]
    mean_rate_for_user = data_for_user[:,2].mean()
    mean_rate_user.append([user,mean_rate_for_user])


In [15]:
mean_rate_user[:5]

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466]]

In [20]:
data_for_user = data[data[:,0] == 1,:]
data_for_user[:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [21]:
aa = np.array(mean_rate_user,dtype=np.float32)
aa

array([[  1.00000000e+00,   4.18867922e+00],
       [  2.00000000e+00,   3.71317840e+00],
       [  3.00000000e+00,   3.90196085e+00],
       ..., 
       [  6.03800000e+03,   3.79999995e+00],
       [  6.03900000e+03,   3.87804890e+00],
       [  6.04000000e+03,   3.57771254e+00]], dtype=float32)

In [22]:
aa.shape

(6040, 2)

In [23]:
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [24]:
data[:,0] == 1

array([ True,  True,  True, ..., False, False, False], dtype=bool)