In [1]:
import numpy as np

In [2]:
data1 = [6,12,3,4]

In [3]:
arr1 = np.array(data1)
arr1

array([ 6, 12,  3,  4])

In [4]:
arr1.shape

(4,)

In [5]:
data2 = [[1,2,3,4],
        [5,6,7,8]]

In [6]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [8]:
np.zeros([3,6])

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
arr1 + arr2

array([[ 7, 14,  6,  8],
       [11, 18, 10, 12]])

In [15]:
arr = np.arange(10)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[5]

5

In [19]:
arr[5:]

array([5, 6, 7, 8, 9])

In [20]:
arr[5:] = 12

In [21]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12])

In [22]:
data = np.random.randn(7,4)

In [23]:
data

array([[-0.05534528,  1.59082216, -0.37640239, -0.21220787],
       [ 0.70169301,  1.39492817, -1.55668056, -0.41488667],
       [ 0.84187581,  0.35850294, -1.99773987, -0.34996474],
       [ 0.06148863, -0.89227374, -0.24961439, -1.12010958],
       [ 1.34350644, -0.44795621,  0.77346418,  0.53333399],
       [ 1.10480029,  2.35996409,  0.42421181,  0.67122852],
       [-0.3768283 , -0.71707496, -0.73728444,  0.44362682]])

In [24]:
arr = np.arange(1,10)

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [27]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [28]:
x = np.random.randn(9)
y = np.random.randn(9)

In [29]:
x

array([-0.20738854,  1.00627156,  2.12965165, -0.76781974, -0.37740204,
       -0.33493777, -0.8042131 ,  1.39659799, -0.93691913])

In [30]:
y

array([ 0.26370532, -0.88338789,  0.30768   ,  0.05410303,  1.02878776,
       -0.2317974 ,  1.14412043,  1.43118746,  2.14182527])

In [31]:
np.maximum(x,y)

array([ 0.26370532,  1.00627156,  2.12965165,  0.05410303,  1.02878776,
       -0.2317974 ,  1.14412043,  1.43118746,  2.14182527])

In [32]:
arr = np.random.randn(5,4)

In [33]:
arr

array([[  1.12743219e-01,   6.76766849e-01,  -4.87400056e-01,
          1.86989523e+00],
       [ -7.01378891e-01,   2.14042997e+00,  -3.12786935e-01,
         -2.17712245e-03],
       [  1.64318871e+00,  -1.39358832e+00,  -1.02143294e+00,
         -7.95993751e-01],
       [ -2.82105578e+00,   4.97881223e-01,  -8.89986538e-01,
          1.39582623e+00],
       [ -1.40058960e-01,  -1.76319571e-01,   1.72471730e+00,
         -3.52646755e-01]])

In [34]:
arr.sum()

0.96662310547104502

In [35]:
arr.sum(axis=0)

array([-1.90656171,  1.74517015, -0.98688917,  2.11490383])

In [36]:
arr.sum(axis=1)

array([ 2.17200525,  1.12408702, -1.5678263 , -1.81733487,  1.05569201])

In [37]:
arr > 0

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [ True, False, False, False],
       [False,  True, False,  True],
       [False, False,  True, False]], dtype=bool)

In [38]:
(arr > 0).sum()

8

In [41]:
arr = np.random.randn(9)

In [42]:
arr

array([ 1.23713951,  0.5390347 ,  0.2069542 , -0.38302851, -0.0587435 ,
        1.10509711,  0.52867941, -0.89742738,  0.49519229])

In [43]:
np.sort(arr)

array([-0.89742738, -0.38302851, -0.0587435 ,  0.2069542 ,  0.49519229,
        0.52867941,  0.5390347 ,  1.10509711,  1.23713951])

In [44]:
np.sort(arr)[::-1]

array([ 1.23713951,  1.10509711,  0.5390347 ,  0.52867941,  0.49519229,
        0.2069542 , -0.0587435 , -0.38302851, -0.89742738])

In [45]:
arr = np.random.randn(5,3)

In [46]:
arr

array([[ 0.2919903 , -0.33001194, -0.64002216],
       [-0.312179  , -0.42482594, -0.99749146],
       [ 1.37598998, -0.19071697, -0.3114135 ],
       [-2.97797115,  0.27424471, -0.12261886],
       [ 0.20039966, -0.42885884,  1.05092103]])

In [47]:
np.sort(arr,axis=0)

array([[-2.97797115, -0.42885884, -0.99749146],
       [-0.312179  , -0.42482594, -0.64002216],
       [ 0.20039966, -0.33001194, -0.3114135 ],
       [ 0.2919903 , -0.19071697, -0.12261886],
       [ 1.37598998,  0.27424471,  1.05092103]])

In [48]:
np.sort(arr,axis=1)

array([[-0.64002216, -0.33001194,  0.2919903 ],
       [-0.99749146, -0.42482594, -0.312179  ],
       [-0.3114135 , -0.19071697,  1.37598998],
       [-2.97797115, -0.12261886,  0.27424471],
       [-0.42885884,  0.20039966,  1.05092103]])

In [49]:
large_arr = np.random.randn(150)

In [50]:
large_arr

array([ 0.7832665 ,  0.67003127, -0.3920073 , -0.32002413, -1.11484898,
       -0.6723919 , -0.30371082,  0.50492279,  0.14059059,  2.04424814,
        0.33472897,  0.81481455, -0.01812282,  0.84020382,  0.42863343,
        0.59273429, -0.25055368,  0.32956846,  0.00745571, -1.45341968,
       -0.65060559, -0.93989632, -1.46366822,  0.1827084 , -0.50831521,
       -2.02453696, -0.92305827, -0.22139884,  0.20923996, -0.59649294,
        0.93772629,  0.84797001, -0.58231516,  1.17183672,  0.2687077 ,
        0.45653525, -1.00744969, -0.24468399,  0.66388767,  1.64771897,
       -0.82872209, -0.87902901, -0.92033044,  0.40166174,  0.72833904,
        1.23271362,  0.24843475, -0.30123051,  0.40197026,  1.07767392,
        0.95844064,  0.03285592, -0.02807096,  0.66505499,  0.93112133,
        1.41834563, -0.97501821, -0.71075445,  2.39074527,  0.46692517,
        0.17976749,  0.29974621, -0.79512506, -0.05752992, -1.6673626 ,
        1.08843196,  1.848039  , -0.23237287, -1.08469186, -0.90

In [53]:
np.sort(large_arr)

array([-2.67717546, -2.02453696, -1.84942463, -1.80954835, -1.7561408 ,
       -1.6673626 , -1.48967991, -1.46366822, -1.45341968, -1.41566278,
       -1.2112275 , -1.11814727, -1.11484898, -1.0918519 , -1.08469186,
       -1.08408456, -1.02822273, -1.00757998, -1.00744969, -0.97501821,
       -0.97189439, -0.960784  , -0.93989632, -0.92305827, -0.92033044,
       -0.91616801, -0.90061858, -0.87902901, -0.87144928, -0.82872209,
       -0.79512506, -0.72458117, -0.71075445, -0.6723919 , -0.65060559,
       -0.61771647, -0.59991442, -0.59649294, -0.59470246, -0.58620458,
       -0.58524321, -0.58231516, -0.52567857, -0.50831521, -0.4952546 ,
       -0.44002683, -0.41532352, -0.3920073 , -0.35887517, -0.32002413,
       -0.30661235, -0.30371082, -0.30123051, -0.26621538, -0.25869534,
       -0.25055368, -0.24468399, -0.23237287, -0.22418369, -0.22411931,
       -0.22198377, -0.22139884, -0.20002579, -0.1934776 , -0.11769172,
       -0.10661465, -0.10432123, -0.07995912, -0.05752992, -0.02

In [54]:
np.sort(large_arr)[::-1][int(0.05*len(large_arr))]

1.41834562627973